### ISSUE TITLE
Doesn't seem to resolve

### ISSUE THREAD

**Issue by Braunson** [paulredmond/atom-larasnippets#1]
Hitting tab on i.e. `route` and it doesn't work.

**Comment by Braunson** [comment]
Lol had to restart Atom.. sorry, closing

**Comment by paulredmond** [comment]
@Braunson thanks, you can also do `Command + Shift + P` and select `Window: Reload` to refresh your editor window. Restarting works too 👍

**Comment by Braunson** [comment]
@paulredmond Thanks great tip and for the package 😄
